// <auto-generated />
using System;
using ExtensionDKM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtensionDKM.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20260331140450_Init migration")]
    partial class Initmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtensionDKM.Models.Assign", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("Assigns");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Classroom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Classroomid")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousCourseId")
                        .HasColumnType("int");

                    b.Property<int?>("RequirementCourseId")
                        .HasColumnType("int");

                    b.Property<int>("ScoreTableid")
                        .HasColumnType("int");

                    b.Property<int>("Scoreid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Classroomid");

                    b.HasIndex("PreviousCourseId");

                    b.HasIndex("RequirementCourseId");

                    b.HasIndex("ScoreTableid");

                    b.HasIndex("Scoreid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Major", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Score", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("FinalTerm")
                        .HasColumnType("int");

                    b.Property<int>("MidTerm")
                        .HasColumnType("int");

                    b.Property<int>("ProgressTerm")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ExtensionDKM.Models.ScoreTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("ScoresTables");
                });

            modelBuilder.Entity("ExtensionDKM.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("majorid")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("majorid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Assign", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Course", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("Classroomid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Course", "PreviousCourse")
                        .WithMany()
                        .HasForeignKey("PreviousCourseId");

                    b.HasOne("ExtensionDKM.Models.Course", "RequirementCourse")
                        .WithMany()
                        .HasForeignKey("RequirementCourseId");

                    b.HasOne("ExtensionDKM.Models.ScoreTable", "ScoreTable")
                        .WithMany()
                        .HasForeignKey("ScoreTableid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Score", "Score")
                        .WithMany()
                        .HasForeignKey("Scoreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("PreviousCourse");

                    b.Navigation("RequirementCourse");

                    b.Navigation("Score");

                    b.Navigation("ScoreTable");
                });

            modelBuilder.Entity("ExtensionDKM.Models.User", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Major", "major")
                        .WithMany("users")
                        .HasForeignKey("majorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("major");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Course", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Major", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("ExtensionDKM.Models.User", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
