// <auto-generated />
using ExtensionDKM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtensionDKM.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseCourse", b =>
                {
                    b.Property<int>("NextCoursesId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousCoursesId")
                        .HasColumnType("int");

                    b.HasKey("NextCoursesId", "PreviousCoursesId");

                    b.HasIndex("PreviousCoursesId");

                    b.ToTable("CoursePrevious", (string)null);
                });

            modelBuilder.Entity("CourseCourse1", b =>
                {
                    b.Property<int>("RequiredById")
                        .HasColumnType("int");

                    b.Property<int>("RequirementCoursesId")
                        .HasColumnType("int");

                    b.HasKey("RequiredById", "RequirementCoursesId");

                    b.HasIndex("RequirementCoursesId");

                    b.ToTable("CourseRequirement", (string)null);
                });

            modelBuilder.Entity("ExtensionDKM.Models.Assign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Assigns");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SS")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int?>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignId")
                        .HasColumnType("int");

                    b.Property<int>("FinalTerm")
                        .HasColumnType("int");

                    b.Property<int>("MidTerm")
                        .HasColumnType("int");

                    b.Property<int>("ProgressTerm")
                        .HasColumnType("int");

                    b.Property<int>("ScoreTableId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignId")
                        .IsUnique();

                    b.HasIndex("ScoreTableId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ExtensionDKM.Models.ScoreTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("ScoresTables");
                });

            modelBuilder.Entity("ExtensionDKM.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ExtensionDKM.Models.Lecturer", b =>
                {
                    b.HasBaseType("ExtensionDKM.Models.User");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Lecturer");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Student", b =>
                {
                    b.HasBaseType("ExtensionDKM.Models.User");

                    b.Property<int>("K")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreTableId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("CourseCourse", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("NextCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("PreviousCoursesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseCourse1", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("RequiredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("RequirementCoursesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtensionDKM.Models.Assign", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Student", "Student")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Classroom", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Course", "Course")
                        .WithMany("Classrooms")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Lecturer", "Lecturer")
                        .WithMany("Classrooms")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.Room", "Room")
                        .WithMany("Classrooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Lecturer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Score", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Assign", "Assign")
                        .WithOne("Score")
                        .HasForeignKey("ExtensionDKM.Models.Score", "AssignId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ExtensionDKM.Models.ScoreTable", "ScoreTable")
                        .WithMany("Scores")
                        .HasForeignKey("ScoreTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assign");

                    b.Navigation("ScoreTable");
                });

            modelBuilder.Entity("ExtensionDKM.Models.ScoreTable", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Student", "Student")
                        .WithOne("ScoreTable")
                        .HasForeignKey("ExtensionDKM.Models.ScoreTable", "StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExtensionDKM.Models.User", b =>
                {
                    b.HasOne("ExtensionDKM.Models.Major", "Major")
                        .WithMany("Users")
                        .HasForeignKey("MajorId");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Assign", b =>
                {
                    b.Navigation("Score");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Major", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Room", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("ExtensionDKM.Models.ScoreTable", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Lecturer", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("ExtensionDKM.Models.Student", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ScoreTable");
                });
#pragma warning restore 612, 618
        }
    }
}
